packages:
  - "apps/*"
  - "libs/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': set this to true or false
  '@prisma/engines': true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
